services:
  app-usuario:
    volumes:
      - ./apps/app-usuario:/app/apps/app-usuario
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - /app/node_modules
      - /app/apps/app-usuario/node_modules
      - /app/packages/shared/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/api/node_modules

  app-conductor:
    volumes:
      - ./apps/app-conductor:/app/apps/app-conductor
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - /app/node_modules
      - /app/apps/app-conductor/node_modules

  panel-admin:
    volumes:
      - ./apps/panel-admin:/app/apps/panel-admin
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - /app/node_modules
      - /app/apps/panel-admin/node_modules