import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
// Gate 2 — aprobación dual
test("aprobación dual impide autoaprobación",()=>{const s=read("supabase/migrations/20260720001000_p2_madurez_operativa.sql");assert.match(s,/aprobada_por <> solicitada_por/);assert.match(s,/APROBADOR_DEBE_SER_DISTINTO/);assert.match(s,/for update/);});
test("capacidades granulares pueden conceder o revocar",()=>{const s=read("supabase/migrations/20260720001000_p2_madurez_operativa.sql");assert.match(s,/admin_capacidades/);assert.match(s,/coalesce\(\(select ac\.concedida/);});
// Gate 1 — exportación limitada, neutralizada y trazada
test("exportación queda limitada, neutralizada y trazada",()=>{const s=read("apps/panel-admin/src/app/api/exportaciones/pagos/route.ts");assert.match(s,/LIMITE_FILAS=10_000/);assert.match(s,/\^\[=\+\\-@\]/);assert.match(s,/sha256/);assert.match(s,/admin_completar_exportacion/);});
test("dashboard de auditoría consulta denegaciones y exportaciones",()=>{const s=read("apps/panel-admin/src/app/auditoria/page.tsx");assert.match(s,/auditoria_admin_seguridad/);assert.match(s,/exportaciones_admin/);assert.match(s,/auditoria:leer/);});
test("el dashboard verifica auditoria:leer antes de consultar datos",()=>{const s=read("apps/panel-admin/src/app/auditoria/page.tsx");assert.match(s,/admin_tiene_permiso/);assert.match(s,/auditoria:leer/);});
// Sprint 1 — bypass cerrar
test("operaciones sensibles exigen aprobación dual válida en SQL",()=>{const s=read("supabase/migrations/20260720001200_sprint1_bypass_cerrar.sql");assert.match(s,/admin_validar_aprobacion/);assert.match(s,/admin_ejecutar_aprobacion/);assert.match(s,/admin_ajustar_precio_final/);assert.match(s,/admin_ejecutar_pago/);assert.match(s,/admin_suspender_conductor/);assert.match(s,/admin_registrar_no_presentacion/);assert.match(s,/admin_registrar_cancelacion_injustificada/);assert.match(s,/APROBACION_PAYLOAD_NO_COINCIDE/);assert.match(s,/APROBACION_REQUERIDA/);});
test("servicios TypeScript migrados a RPC y bloquean estados críticos",()=>{const s=read("packages/api/src/services/admin.ts");assert.match(s,/admin_ajustar_precio_final/);assert.match(s,/admin_suspender_conductor/);assert.match(s,/admin_registrar_no_presentacion/);assert.match(s,/admin_registrar_cancelacion_injustificada/);assert.match(s,/ESTADOS_CRITICOS_TRASLADO/);});
// Sprint 2 — permisos efectivos
test("migración incluye pagos:exportar en matriz de admin_tiene_permiso",()=>{const s=read("supabase/migrations/20260722001300_sprint2_permisos_efectivos.sql");assert.match(s,/pagos:exportar/);assert.match(s,/admin_conceder_capacidad/);assert.match(s,/admin_listar_capacidades_catalogo/);assert.match(s,/admin_listar_capacidades/);assert.match(s,/NO_PUEDES_OTORGARTE_CAPACIDADES_ADMINISTRAR/);assert.match(s,/MOTIVO_OBLIGATORIO/);});
test("RLS policies reemplazan es_admin con admin_tiene_permiso",()=>{const s=read("supabase/migrations/20260722001300_sprint2_permisos_efectivos.sql");assert.match(s,/drop policy if exists admin_acceso_total_pagos/);assert.match(s,/drop policy if exists admin_acceso_total_conductores/);assert.match(s,/admin_tiene_permiso\('pagos:leer'\)/);assert.match(s,/admin_tiene_permiso\('conductores:leer'\)/);});
test("rollo-admin.ts: RUTA_A_CAPACIDAD y obtenerCapacidadParaRuta",()=>{const s=read("apps/panel-admin/src/lib/roles-admin.ts");assert.match(s,/RUTA_A_CAPACIDAD/);assert.match(s,/obtenerCapacidadParaRuta/);assert.match(s,/PermisoAdmin/);assert.match(s,/capacidades:administrar/);});
test("middleware verifica capacidad efectiva via admin_tiene_permiso",()=>{const s=read("apps/panel-admin/src/middleware.ts");assert.match(s,/obtenerCapacidadParaRuta/);assert.match(s,/admin_tiene_permiso/);assert.match(s,/capacidad_insuficiente/);});
test("exportación endurecida: pagos:exportar, filtros reales, rango fechas",()=>{const s=read("apps/panel-admin/src/app/api/exportaciones/pagos/route.ts");assert.match(s,/pagos:exportar/);assert.match(s,/DIAS_MAX=90/);assert.match(s,/pagos:leer/);assert.match(s,/EXPORT_AUDIT_FAILED/);});
test("permisos-admin.ts incluye pagos:exportar",()=>{const s=read("packages/api/src/services/permisos-admin.ts");assert.match(s,/pagos:exportar/);assert.match(s,/finanzas/);assert.match(s,/direccion/);});
test("existe servicio admin-capacidades.ts y se exporta",()=>{const s=read("packages/api/src/services/admin-capacidades.ts");assert.match(s,/listarCatalogoCapacidades/);assert.match(s,/listarCapacidadesAdmin/);assert.match(s,/concederCapacidadAdmin/);});
test("index de servicios exporta admin-capacidades",()=>{const s=read("packages/api/src/services/index.ts");assert.match(s,/admin-capacidades/);});
test("existe página de gestión de capacidades",()=>{assert.ok(fs.existsSync("apps/panel-admin/src/app/capacidades/page.tsx"));const s=read("apps/panel-admin/src/app/capacidades/page.tsx");assert.match(s,/listarCatalogoCapacidades/);assert.match(s,/concederCapacidadAdmin/);assert.match(s,/capacidades:administrar/);});
test("carga y accesibilidad con sesión real",()=>{assert.ok(fs.existsSync("tests/load/panel-admin-degradacion.js"));const s=read("apps/panel-admin/tests/a11y-real/auditoria-sesiones.spec.ts");assert.match(s,/ADMIN_STORAGE_STATE/);assert.match(s,/AxeBuilder/);});
