import type { EstadoTraslado } from "../types/traslado";

// PRD §6 — los 32 estados del traslado, en el orden en que aparecen en la tabla
export const ESTADOS_TRASLADO: EstadoTraslado[] = [
  "usuario_pendiente_verificacion",
  "usuario_verificado",
  "solicitud_creada",
  "documentacion_pendiente",
  "documentacion_en_revision",
  "documentacion_validada",
  "cotizacion_generada",
  "cotizacion_aceptada",
  "servicio_confirmado",
  "pendiente_de_conductor",
  "conductor_asignado",
  "conductor_en_camino_al_origen",
  "conductor_en_punto_de_recoleccion",
  "verificacion_vehiculo_en_proceso",
  "evidencia_inicial_en_proceso",
  "evidencia_inicial_completada",
  "vehiculo_recibido",
  "traslado_en_curso",
  "incidencia_reportada",
  "llegada_a_destino",
  "evidencia_final_en_proceso",
  "evidencia_final_completada",
  "entrega_confirmada",
  "pago_pendiente",
  "pago_completado",
  "servicio_cerrado",
  "servicio_cancelado",
  "traslado_fallido",
  "dano_no_reportado_en_revision",
  "reclamo_abierto",
  "reclamo_resuelto",
  "cierre_operativo_con_incidencia_abierta",
  "disputa_abierta",
  "disputa_resuelta"
];

export const ETIQUETA_ESTADO_TRASLADO: Record<EstadoTraslado, string> = {
  usuario_pendiente_verificacion: "Usuario pendiente de verificación",
  usuario_verificado: "Usuario verificado",
  solicitud_creada: "Solicitud creada",
  documentacion_pendiente: "Documentación pendiente",
  documentacion_en_revision: "Documentación en revisión",
  documentacion_validada: "Documentación validada",
  cotizacion_generada: "Cotización generada",
  cotizacion_aceptada: "Cotización aceptada · pago pendiente",
  servicio_confirmado: "Servicio confirmado",
  pendiente_de_conductor: "Pendiente de conductor",
  conductor_asignado: "Conductor asignado",
  conductor_en_camino_al_origen: "Conductor en camino al origen",
  conductor_en_punto_de_recoleccion: "Conductor en punto de recolección",
  verificacion_vehiculo_en_proceso: "Verificación de vehículo en proceso",
  evidencia_inicial_en_proceso: "Evidencia inicial en proceso",
  evidencia_inicial_completada: "Evidencia inicial completada",
  vehiculo_recibido: "Vehículo recibido",
  traslado_en_curso: "Traslado en curso",
  incidencia_reportada: "Incidencia reportada",
  llegada_a_destino: "Llegada a destino",
  evidencia_final_en_proceso: "Evidencia final en proceso",
  evidencia_final_completada: "Evidencia final completada",
  entrega_confirmada: "Entrega confirmada",
  pago_pendiente: "Pago pendiente",
  pago_completado: "Pago completado",
  servicio_cerrado: "Servicio cerrado",
  servicio_cancelado: "Servicio cancelado",
  traslado_fallido: "Traslado fallido",
  dano_no_reportado_en_revision: "Daño no reportado en revisión",
  reclamo_abierto: "Reclamo abierto",
  reclamo_resuelto: "Reclamo resuelto",
  cierre_operativo_con_incidencia_abierta: "Cierre operativo con incidencia abierta",
  disputa_abierta: "Disputa abierta",
  disputa_resuelta: "Disputa resuelta"
};
